package:
  name: 'niondata'
  version: '15.6.2'

source:
  git_rev: 15.6.2
  git_url: https://github.com/nion-software/niondata.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.9
    - nionutils >=0.4.5,<5.0.0
    - scipy
    - numpy >=1.21,<2.0

test:
  imports:
    - nion.data
    - nion.data.test

about:
  home: https://github.com/nion-software/niondata
  license: Apache-2.0
  summary: Nion UI classes.
  description: "A library of useful data processing classes."

extra:
  recipe-maintainers:
    cmeyer
