package:
  name: 'niondata'
  version: '0.13.12'

source:
  git_rev: 0.13.12
  git_url: https://github.com/nion-software/niondata.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - setuptools
  run:
    - python >=3.7
    - nionutils >=0.3.10,<0.4.0
    - scipy
    - numpy

test:
  imports:
    - nion.data
    - nion.data.test

about:
  home: https://github.com/nion-software/niondata
  license: Apache-2.0
  summary: Nion UI classes.
  description: "A library of useful data processing classes."

extra:
  recipe-maintainers:
    cmeyer
